### ISSUE TITLE
Fetching more detailed job exit reason and status

### ISSUE THREAD

**Issue by typhoonzero** [PaddlePaddle/cloud#195]
Get detailed trainer exit status(like FPE) and display when user called `paddlecloud get jobs`.

General error codes are in https://www.student.cs.uwaterloo.ca/~cs136/seashell/docs/seashell-error-codes.html#%28part._.Error_code_136_-_.Erroneous_.Arithmetic_.Operation%29

And how to get pod exit status: https://kubernetes.io/docs/tasks/debug-application-cluster/determine-reason-pod-failure/

Errror status is at `.status.containerStatuses[id].lastState.terminated`, sample:

```yaml
      terminated:
        containerID: docker://bfce416f52454e39dd9d69df751b521eadf6afb64065d679f9c34e5e46a93231
        exitCode: 128
        finishedAt: 2017-07-03T02:31:12Z
        message: 'mkdir /mnt/hdfs_mulan: file exists'
        reason: ContainerCannotRun
        startedAt: null
```
