### ISSUE TITLE
Deploy cloud 到 Kubernetes时出错

### ISSUE THREAD

**Issue by Daemon007** [PaddlePaddle/cloud#217]
执行`kubectl create -f cloud_deployment.yaml`
报错`Error from server(BadRequest): error when creating "/cloud-deployment.yaml": Deployment in version v1beta1 cannot be handled as a Deployment: [pos 316]:json: expect char '"' but got char '8'`

请问该如何解决？

yaml配置文件：
```
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: paddle-cloud
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: paddle-cloud
    spec:
      volumes:
      - name: cert-volume
        hostPath:
          path: /home/pcloud/data/certs
      - name: mysql-data
        hostPath:
          path: /home/pcloud/data/mysql
      - name: settings
        hostPath:
          path: /home/pcloud/data/settings.py
      #- name: email-tmp-msg:
      #  hostPath:
      #    path: /home/pcloud/templates/email_confirmation_message.txt
      #- name: email-tmp-subj:
      #  hostPath:
      #    path: /home/pcloud/templates/email_confirmation_subject.txt
      #- name: homepage
      #  hostPath:
      #    path: /home/pcloud/templates/homepage.html
      # - name: data-storage
      #   cephfs:
      #     name: cephfs
      #     monitors: ["172.19.32.166:6789"]
      #     path: "/"
      #     user: "admin"
      #     secretRef:
      #       name: ceph-secret
      containers:
      - name: paddle-cloud
        imagePullPolicy: Always
        image: registry.vm-1:5000/paddlecloud
        volumeMounts:
        - name: cert-volume
          mountPath: /certs
        - name: settings
          mountPath: /pcloud/paddlecloud/settings.py
        # - name: data-storage
        #   mountPath: /pfs
        #- name: homepage
        #  mountPath: /pcloud/paddlecloud/templates/homepage.html
        #- name: email-tmp-msg:
        #  mountPath: /pcloud/paddlecloud/notebook/account/email/email_confirmation_message.txt
        #- name: email-tmp-subj:
        #  mountPath: /pcloud/paddlecloud/notebook/account/email/email_confirmation_subject.txt
        ports:
        - containerPort: 8000
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PORT
          value: 8000
#        livenessProbe:
#         httpGet:
#           path: /healthz/
#           port: 8000
#           httpHeaders:
#           - name: User-Agent
#             value: kubernetes-health-check
#         initialDelaySeconds: 3
#         periodSeconds: 5
      - name: mysql
        image: mysql:5.7
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: root
      nodeSelector:
        kubernetes.io/hostname: vm-2,vm-3,vm-4
```
