### ISSUE TITLE
Need a readable message when the configuration file is invalid

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#514]
```yaml
datacenters:
- name: dlnel
  username: <username>
  password: <password>
  endpoint: http://example.cloud.org
  current-datacenter: <dc>
```
The Go program panic:
```bash
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x50 pc=0x1279a29]

goroutine 1 [running]:
github.com/PaddlePaddle/cloud/go/paddlecloud.jobs(0x10b2830, 0xc420063860)
	/go/src/github.com/PaddlePaddle/cloud/go/paddlecloud/get.go:148 +0x69
github.com/PaddlePaddle/cloud/go/paddlecloud.(*GetCommand).Execute(0xc4200139ed, 0x1453ee0, 0xc420012270, 0xc420063860, 0x0, 0x0, 0x0, 0x131858a)
	/go/src/github.com/PaddlePaddle/cloud/go/paddlecloud/get.go:47 +0x1f0
github.com/google/subcommands.(*Commander).Execute(0xc42004d1f0, 0x1453ee0, 0xc420012270, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/google/subcommands/subcommands.go:141 +0x386
github.com/google/subcommands.Execute(0x1453ee0, 0xc420012270, 0x0, 0x0, 0x0, 0xc4200001a0)
	/go/src/github.com/google/subcommands/subcommands.go:371 +0x5f
main.main()
	/go/src/github.com/cloud/go/cmd/paddlecloud/paddlecloud.go:31 +0x3b2
```
