### ISSUE TITLE
Discuss about activate datacenter in the paddlecloud

### ISSUE THREAD

**Issue by Yancey1989** [PaddlePaddle/cloud#59]
As the [Paddle Client Configuration](https://github.com/PaddlePaddle/cloud/pull/58#pullrequestreview-39381467),  we can configure the activate datacenter in each datacenter item, this means we can configure multiple activate datacenter.But in the [cloud/config.go](https://github.com/PaddlePaddle/cloud/blob/develop/go/paddlecloud/config.go#L29), the activate datacenter is only a pointer, so I think we can add a field: *activate_dc* in the configuration file:

```yaml
datacenters:
- name: datacenter1
  username: user1
  password: secret
  endpoint: http://cloud.paddlepaddle.org
activate_dc: datacenter1
``` 

If this is reasonable, I can make a PR for this one.
